# -*- coding: utf-8 -*-
"""atividade-pandas-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nkb6ASmuXHBfiSA-isQlWbzi2zwr792k
"""

import pandas as pd
import numpy as np

# 1. Ler o conjunto de dados
df = pd.read_csv("heart.csv")

# 2. Primeiras linhas
print("2. Primeiras linhas:")
print(df.head())

# 3. Últimas linhas
print("\n3. Últimas linhas:")
print(df.tail())

# 4. Dimensões
print("\n4. Dimensões do DataFrame:")
print(df.shape)

# 5. Informações do DataFrame
print("\n5. Informações sobre o DataFrame:")
print(df.info())

# 6. Estatísticas descritivas
print("\n6. Estatísticas descritivas:")
print(df.describe())

# 7. Dados ausentes
print("\n7. Verificação de dados ausentes por coluna:")
print(df.isnull().sum())

# 8. Coluna 'age' como array NumPy
idade_array = df['age'].to_numpy()
print("\n8. Coluna 'age' como array NumPy:")
print(idade_array)

# 9. Duas colunas como DataFrame
colunas_selecionadas = df[['age', 'chol']]
print("\n9. Duas colunas como DataFrame:")
print(colunas_selecionadas.head())

# 10. Linha específica com loc (índice 10)
print("\n10. Linha com índice 10:")
print(df.loc[10])

# 11. Linhas com condições (idade > 50 e colesterol > 200)
condicoes = df.loc[(df['age'] > 50) & (df['chol'] > 200)]
print("\n11. Linhas com idade > 50 e colesterol > 200:")
print(condicoes)